"""Reviewed row specs for layers/tables/obstacle_correspondence.json.

Candidate groups come from derive.py (cross-lens equivalences in layers/diagnosis.json). Each row below was reviewed
against the cited teachings. Lens, name, grade and user_facing are NOT typed here: build.py computes them from
diagnosis.json and data/ (grade = weakest diagnosis.json grade on the edges that connect the members).
Members whose only support is an unresolved citation are left out and named in `pending_members`.
"""

ROWS = [
    {
        "id": "oc:raga-kamacchanda-lobha",
        "title": "rāga ↔ kāma ↔ kāmacchanda / taṇhā / lobha ↔ lobha (kaṣāya)",
        "members": [
            {"dx": "dx:klesa-raga", "term": "rāga (a kleśa)", "cites": ["tea:yoga-sutra:2.7", "tea:yoga-bhasya:2.7", "tea:yoga-sutra:2.4"]},
            {"dx": "dx:gita-kama-krodha", "term": "kāma (one enemy with krodha, born of rajas)", "cites": ["tea:bhagavad-gita:3.37", "tea:bhagavad-gita:2.62"]},
            {"dx": "dx:nivarana-kamacchanda", "term": "kāmacchanda (a nīvaraṇa)", "cites": ["tea:satipatthana-sutta:mn10:36", "tea:mahasatipatthana-sutta:dn22:13"]},
            {"dx": "dx:root-lobha", "term": "lobha; the mind 'with lust' (sarāga)", "cites": ["tea:satipatthana-sutta:mn10:34"]},
            {"dx": "dx:fetter-kamaraga", "term": "kāmarāga (sensual lust, one of the five lower fetters)", "cites": ["tea:visuddhimagga:22.p683"]},
            {"dx": "dx:tanha", "term": "taṇhā (origin of suffering)", "cites": ["tea:mahasatipatthana-sutta:dn22:19", "tea:mahasatipatthana-sutta:dn22:20"]},
            {"dx": "dx:kasaya-lobha", "term": "lobha (one of the four kaṣāyas)", "cites": ["tea:tattvartha-sutra:8.9", "tea:tattvartha-sutra:8.2"]},
        ],
        "what_is_shared": "Each text names a pull toward what is found pleasant and dear, and treats it as binding and as something to let go. YS: attachment rests on pleasure (YS 2.7); Vyāsa glosses it as greed, thirst and covetousness (gardha, tṛṣṇā, lobha) for the pleasure or its means, preceded by the memory of pleasure (YB 2.7). Gītā: from dwelling on objects comes attachment, from attachment desire (BhG 2.62); desire-anger is 'the enemy here' (BhG 3.37). Suttas: sensual desire (kāmacchanda) is known as present or absent, as arising and as abandoned (MN 10:36; DN 22:13); craving (taṇhā) that delights here and there is the origin of suffering, and its fading away is cessation (DN 22:19–20). TS: greed (lobha) is one of the four passions (TS 8.9), because of which the soul takes in karmic matter (TS 8.2).",
        "what_differs": "Rāga is not kāmacchanda, and neither is lobha. (1) Framework: YS rāga is one of five kleśas growing in the field of avidyā (YS 2.4). The Gītā's kāma is born of the guṇa rajas and is one enemy with anger (BhG 3.37). Kāmacchanda is a hindrance: a state to be noticed and abandoned in meditation (MN 10:36). Taṇhā is the origin of suffering (DN 22:19). Jain lobha is a passion-felt deluding karma (kaṣāya-vedanīya, TS 8.9) and a literal cause of karmic matter binding the soul (TS 8.2). (2) Scope: YS rāga covers any remembered pleasure and its means (YB 2.7). Kāmacchanda is sensual desire. Taṇhā in DN 22 also includes craving for being and for non-being (DN 22:19); the Yoga puts the wish to go on being under a different kleśa (abhiniveśa, YS 2.9). Jain lobha comes in four intensities, anantānubandhī to saṃjvalana (TS 8.9), a grading no other lens uses. The Theravāda lists grade it differently, by depth: a hindrance that keeps jhāna from arising (Vism IV), greed as a root of unwholesome consciousness (Vism XIV), and sensual lust as one of the five lower fetters (Vism XXII). (3) What is freed: the Yoga ends in the seer's aloneness (YS 2.25), the suttas in the cessation of craving (DN 22:20), the Jain path in the soul's release from karmic matter (TS 8.2). The self-question behind these three ends is not yet reconciled (row ot:provisional-self-question in one_truth.json).",
        "extra_cites": ["tea:yoga-sutra:2.9", "tea:yoga-sutra:2.25", "tea:visuddhimagga:4.p146", "tea:visuddhimagga:14.p468"],
        "principle": {"id": "P2-standpoint", "reason": "The same pull is described from different standpoints: an affliction of mis-taken identity (YS), a strand of nature (BhG), a hindrance to be known in meditation and the origin of suffering (suttas), a passion that binds karmic matter (TS). None of these accounts is absorbed into another."},
        "pending_members": [],
    },
    {
        "id": "oc:dvesa-byapada-krodha",
        "title": "dveṣa ↔ krodha (Gītā) ↔ byāpāda / dosa ↔ krodha (kaṣāya)",
        "members": [
            {"dx": "dx:klesa-dvesa", "term": "dveṣa (a kleśa)", "cites": ["tea:yoga-sutra:2.8", "tea:yoga-bhasya:2.8"]},
            {"dx": "dx:gita-kama-krodha", "term": "krodha (born of kāma and rajas)", "cites": ["tea:bhagavad-gita:2.62", "tea:bhagavad-gita:2.63", "tea:bhagavad-gita:3.37"]},
            {"dx": "dx:nivarana-byapada", "term": "byāpāda (a nīvaraṇa)", "cites": ["tea:satipatthana-sutta:mn10:36", "tea:mahasatipatthana-sutta:dn22:13"]},
            {"dx": "dx:root-dosa", "term": "dosa; the mind 'with hatred' (sadosa)", "cites": ["tea:satipatthana-sutta:mn10:34", "tea:visuddhimagga:14.p470"]},
            {"dx": "dx:fetter-patigha", "term": "paṭigha (ill will as one of the five lower fetters)", "cites": ["tea:visuddhimagga:22.p683"]},
            {"dx": "dx:kasaya-krodha", "term": "krodha (one of the four kaṣāyas)", "cites": ["tea:tattvartha-sutra:8.9", "tea:tattvartha-sutra:8.2"]},
        ],
        "what_is_shared": "Each names a recoil from what is painful or opposed, and treats it as binding. YS: aversion rests on pain (YS 2.8); Vyāsa: it is recoil (pratigha), resentment (manyu), the wish to strike (jighāṃsā) and anger (krodha) toward pain or its means, preceded by the memory of pain (YB 2.8). Gītā: from desire, anger arises; from anger, delusion, confused memory and the loss of understanding (BhG 2.62–63). Suttas: ill will (byāpāda) is known as present or absent, as arising and as abandoned (MN 10:36; DN 22:13); a mind 'with hatred' (sadosa) is known as such (MN 10:34). TS: anger (krodha) is one of the four passions (TS 8.9), by which the soul takes in karmic matter (TS 8.2).",
        "what_differs": "(1) Where anger comes from: the Gītā derives anger from desire (BhG 2.62). Anger is downstream of kāma, and the two are one enemy (BhG 3.37). YS makes dveṣa a kleśa of its own, resting on remembered pain, parallel to rāga and in the same field of avidyā (YS 2.4, 2.8). (2) In the suttas cited here, ill will is a hindrance and a quality of mind to be known (MN 10:34, 10:36). These passages do not ground it in a self or in karmic matter. (3) Jain krodha is a karma-type (conduct-deluding, passion-felt) with four intensities (TS 8.9), and it binds matter to the soul (TS 8.2). Neither the Yoga nor the suttas have this material account of bondage. (4) The Gītā's chain goes on from anger to the loss of understanding (BhG 2.63); YS gives no such chain for dveṣa. (5) The Theravāda lists place hate at more than one depth: as a root of unwholesome consciousness whose mark is ferocity (Vism XIV), and as ill will (paṭigha) among the five lower fetters (Vism XXII). Vyāsa's word pratigha (YB 2.8) is the Sanskrit form of paṭigha, but the shared word does not make the frameworks the same.",
        "extra_cites": ["tea:yoga-sutra:2.4"],
        "principle": {"id": "P2-standpoint", "reason": "One recoil, seen from different standpoints: a kleśa resting on remembered pain (YS), a link in the chain from desire (BhG), a hindrance known in meditation (suttas), a passion that binds karmic matter (TS). Each account keeps its own causal story."},
        "pending_members": [],
    },
    {
        "id": "oc:avidya-moha-mithyadarsana",
        "title": "avidyā (and viparyaya) ↔ moha ↔ mithyādarśana",
        "members": [
            {"dx": "dx:klesa-avidya", "term": "avidyā (the field of the kleśas)", "cites": ["tea:yoga-sutra:2.3", "tea:yoga-sutra:2.4", "tea:yoga-sutra:2.5"]},
            {"dx": "dx:vrtti-viparyaya", "term": "viparyaya (erroneous cognition, a vṛtti)", "cites": ["tea:yoga-sutra:1.8", "tea:yoga-bhasya:1.8"]},
            {"dx": "dx:root-moha", "term": "moha; the mind 'with delusion' (samoha)", "cites": ["tea:satipatthana-sutta:mn10:34", "tea:mahasatipatthana-sutta:dn22:12"]},
            {"dx": "dx:fetter-avijja", "term": "avijjā (ignorance, among the fetters left until the arahat path)", "cites": ["tea:visuddhimagga:22.p682"]},
            {"dx": "dx:jain-mithyadarsana", "term": "mithyādarśana (first cause of bondage)", "cites": ["tea:tattvartha-sutra:8.1", "tea:tattvartha-sutra:8.9"]},
        ],
        "what_is_shared": "Each lens puts a failure to see things as they are at or near the root of bondage. YS: ignorance is the field of the other afflictions (YS 2.4). It takes the impermanent, impure, painful and not-self to be permanent, pure, pleasant and self (YS 2.5). Erroneous cognition (viparyaya) is false knowledge, not established in the object's own form (YS 1.8). Suttas: a mind 'with delusion' (samoha) is known as such (MN 10:34; DN 22:12). TS: wrong view (mithyādarśana) stands first among the five causes of bondage (TS 8.1).",
        "what_differs": "(1) What is not seen: YS avidyā is a specific fourfold mis-taking, and its last item is taking the not-self for the self (YS 2.5). It presupposes a real seer that is mis-taken. The Jain wrong view is counted as a kind of view-deluding karma (mithyātva under darśana-mohanīya, beside right view, TS 8.9): it is itself karmic. In MN 10 delusion is a quality of mind known as present or absent, and the passage states no metaphysics. In the Visuddhimagga ignorance is among the last fetters, abandoned only at the arahat path (Vism XXII). (2) How it is undone: in YS ignorance ends when unwavering discrimination (YS 2.26) brings the seer's aloneness (YS 2.25). In the suttas the way ends in the cessation of craving and in nibbāna (DN 22:20; MN 10:2). In TS bondage ends as its causes are removed, wrong view first (TS 8.1). (3) Within the Yoga, avidyā and viparyaya are graded same-under-standpoint in diagnosis.json: the kleśa seen as a mind-activity. Across the lenses the grade is only partial.",
        "extra_cites": ["tea:yoga-sutra:2.25", "tea:yoga-sutra:2.26", "tea:mahasatipatthana-sutta:dn22:20", "tea:satipatthana-sutta:mn10:2"],
        "principle": {"id": "P2-standpoint", "reason": "Each tradition names the root not-seeing from its own analysis of bondage. The correspondence holds for its function (first among the causes of bondage), not for what is failed to be seen."},
        "pending_members": [],
    },
    {
        "id": "oc:asmita-mana-darpa",
        "title": "asmitā ↔ darpa / abhimāna (Gītā) ↔ māna (kaṣāya)",
        "members": [
            {"dx": "dx:klesa-asmita", "term": "asmitā (I-am-ness)", "cites": ["tea:yoga-sutra:2.6", "tea:yoga-bhasya:2.6"]},
            {"dx": "dx:gita-asuri-sampad", "term": "darpa, abhimāna (in the āsurī sampad)", "cites": ["tea:bhagavad-gita:16.4", "tea:bhagavad-gita:16.5"]},
            {"dx": "dx:kasaya-mana", "term": "māna (one of the four kaṣāyas)", "cites": ["tea:tattvartha-sutra:8.9", "tea:tattvartha-sutra:8.2"]},
            {"dx": "dx:fetter-sakkaya-ditthi", "term": "sakkāya-diṭṭhi (personality view, a lower fetter)", "cites": ["tea:visuddhimagga:17.p570", "tea:visuddhimagga:22.p683"]},
            {"dx": "dx:fetter-mana", "term": "māna (conceit, a fetter left until the arahat path)", "cites": ["tea:visuddhimagga:22.p682", "tea:visuddhimagga:22.p683"]},
        ],
        "what_is_shared": "Each names a false or inflated 'I'. YS: I-am-ness is the seeming identity of the power of the seer and the power of seeing (YS 2.6). Vyāsa: the puruṣa is the seer's power, the buddhi the power of seeing (YB 2.6). Gītā: arrogance and conceit (darpa, abhimāna) belong to the demonic endowment (BhG 16.4), which leads to bondage (BhG 16.5). TS: pride (māna) is one of the four passions (TS 8.9), by which the soul takes in karmic matter (TS 8.2). Visuddhimagga: personality view (sakkāyadiṭṭhi) regards form and the other aggregates as self (Vism XVII) and is one of the five lower fetters; conceit (māna) is a defilement and a fetter that remains until the arahat path (Vism XXII).",
        "what_differs": "Asmitā is not pride. YS 2.6 names a confusion of the seer with its instrument, a structural error that is present even without any haughtiness. The Gītā's darpa and abhimāna and the Jain māna are attitudes of self-exaltation: the Gītā lists them among the marks of a bad endowment (BhG 16.4), and TS grades māna in four intensities (TS 8.9). They meet only in the 'I'. Personality view comes closest to asmitā, since both take something that is not the self as the self. The Yoga also counts that as an error (YS 2.5), but it corrects the error by isolating a real seer (YS 2.25). The Visuddhimagga's remedy is to abandon the view, which is one of the five lower fetters, and conceit remains until the arahat path (Vism XXII). It does not isolate a seer in the view's place. Whether a seer remains is not yet reconciled (row ot:provisional-self-question of one_truth.json).",
        "extra_cites": ["tea:yoga-sutra:2.5", "tea:yoga-sutra:2.25"],
        "principle": {"id": "P2-standpoint", "reason": "Related only through the 'I': a confusion of seer and instrument (YS), an arrogance (BhG), a passion (TS), a view and a conceit to be abandoned (Vism). Each is true within its own standpoint, and the row claims no more than that shared reference."},
        "pending_members": [],
    },
    {
        "id": "oc:dambha-maya",
        "title": "dambha (Gītā) ↔ māyā (kaṣāya)",
        "members": [
            {"dx": "dx:gita-asuri-sampad", "term": "dambha (hypocrisy, in the āsurī sampad)", "cites": ["tea:bhagavad-gita:16.4", "tea:bhagavad-gita:16.5"]},
            {"dx": "dx:kasaya-maya", "term": "māyā (deceit, one of the four kaṣāyas)", "cites": ["tea:tattvartha-sutra:8.9", "tea:tattvartha-sutra:8.2"]},
        ],
        "what_is_shared": "Both name showing oneself as what one is not. Hypocrisy (dambha) heads the Gītā's list of the demonic endowment (BhG 16.4). Deceit (māyā) is one of the four Jain passions (TS 8.9).",
        "what_differs": "The Gītā lists dambha among the marks of an endowment one is 'born to', which leads to bondage (BhG 16.4–5). The Jain māyā is a karma-type with four intensities that binds karmic matter to the soul (TS 8.2, 8.9). The Jain word māyā (deceit) is not the Upaniṣadic māyā, the power by which the māyin projects the world (ŚU 4.9–10): they are the same word with unrelated senses.",
        "extra_cites": ["tea:svetasvatara-upanisad:4.9-10"],
        "principle": {"id": "P2-standpoint", "reason": "One fault, named from an ethical standpoint (a mark of endowment, BhG) and from a karmic one (a passion that binds, TS)."},
        "pending_members": ["dx:carita-raga (linked through deceit in Vism III; its page references do not resolve in data/)"],
    },
    {
        "id": "oc:styana-alasya-thina-middha",
        "title": "styāna, ālasya (and tamas, nidrā) ↔ thina-middha",
        "members": [
            {"dx": "dx:antaraya-styana", "term": "styāna (an antarāya)", "cites": ["tea:yoga-sutra:1.30", "tea:yoga-bhasya:1.30"]},
            {"dx": "dx:antaraya-alasya", "term": "ālasya (an antarāya)", "cites": ["tea:yoga-sutra:1.30", "tea:yoga-bhasya:1.30"]},
            {"dx": "dx:guna-tamas", "term": "tamas (a guṇa)", "cites": ["tea:bhagavad-gita:14.8", "tea:bhagavad-gita:14.13"]},
            {"dx": "dx:vrtti-nidra", "term": "nidrā (a vṛtti)", "cites": ["tea:yoga-sutra:1.10"]},
            {"dx": "dx:nivarana-thina-middha", "term": "thina-middha (a nīvaraṇa)", "cites": ["tea:satipatthana-sutta:mn10:36", "tea:mahasatipatthana-sutta:dn22:13"]},
        ],
        "what_is_shared": "Each names a heaviness or dullness that keeps the mind from its work. YS: dullness (styāna) is the mind's unfitness for work, and laziness (ālasya) is non-engagement from heaviness of body and mind. Both are among the nine obstacles, which are distractions of the mind (YS 1.30; YB 1.30). Gītā: tamas, born of ignorance, binds by heedlessness, idleness and sleep (BhG 14.8). Suttas: dullness and drowsiness (thina-middha) is known as present or absent, as arising and as abandoned (MN 10:36; DN 22:13). The Pali thina and the Sanskrit styāna are the same word.",
        "what_differs": "(1) Counting: YS counts styāna and ālasya as two separate obstacles (YS 1.30), and treats sleep (nidrā) as a mind-activity whose support is the cognition of absence (YS 1.10), not as an obstacle. The suttas join stiffness and torpor into one hindrance (MN 10:36). (2) Kind: the Gītā's tamas is a guṇa of prakṛti that binds the embodied one (BhG 14.5, 14.8). It is a strand of nature present in every being, not a passing state. The obstacles and the hindrance are states that come and go. (3) YS 1.30 lists illness (vyādhi) among the same obstacles. This row does not map bodily conditions and makes no health claim.",
        "extra_cites": ["tea:bhagavad-gita:14.5"],
        "principle": {"id": "P2-standpoint", "reason": "The same dullness appears as two obstacles in the Yoga's analysis of distraction, as a strand of nature in the Gītā, and as one hindrance to be known in the suttas."},
        "pending_members": ["dx:gk-laya (GK 3.42 and 3.35 are cited in diagnosis.json but missing from data/)"],
    },
    {
        "id": "oc:viksepa-uddhacca",
        "title": "cañcala manas, vikṣipta ↔ uddhacca-kukkucca, vikkhitta citta",
        "members": [
            {"dx": "dx:gita-restless-mind", "term": "cañcala manas (the restless mind)", "cites": ["tea:bhagavad-gita:6.34", "tea:bhagavad-gita:6.35", "tea:bhagavad-gita:6.26"]},
            {"dx": "dx:cittabhumi", "term": "vikṣipta (the distracted ground of mind)", "cites": ["tea:yoga-bhasya:1.1"]},
            {"dx": "dx:nivarana-uddhacca-kukkucca", "term": "uddhacca-kukkucca (a nīvaraṇa)", "cites": ["tea:satipatthana-sutta:mn10:36"]},
            {"dx": "dx:citta-vikkhitta", "term": "vikkhitta citta (scattered mind)", "cites": ["tea:satipatthana-sutta:mn10:34"]},
            {"dx": "dx:fetter-uddhacca", "term": "uddhacca (restlessness, a fetter left until the arahat path)", "cites": ["tea:visuddhimagga:14.p469", "tea:visuddhimagga:22.p682"]},
        ],
        "what_is_shared": "Each names a mind that will not stay. Gītā: the mind is restless, turbulent, strong and obstinate, as hard to restrain as the wind (BhG 6.34). It is held by practice and dispassion (BhG 6.35), and wherever it wanders it is to be brought back (BhG 6.26). Vyāsa: samādhi is a property of the mind at every level, and one of its grounds is the distracted (vikṣipta) (YB 1.1). Suttas: restlessness and remorse (uddhacca-kukkucca) is a hindrance known as present or absent (MN 10:36), and a scattered (vikkhitta) mind is known as scattered (MN 10:34).",
        "what_differs": "(1) Vyāsa's distracted mind is one ground in a scale of grounds of mind (YB 1.1). MN 10 only names the scattered mind as something to be known, with no scale (MN 10:34). (2) The hindrance joins restlessness and remorse (kukkucca) into one (MN 10:36). The Gītā passage speaks of restlessness alone. (3) The Gītā names the remedy, practice and dispassion (BhG 6.35). MN 10's approach in this passage is to know the hindrance as present, arising and abandoned (MN 10:36). (4) The Visuddhimagga defines restlessness by its mark of non-calming (Vism XIV). It counts restlessness among the fetters that remain until the arahat path (Vism XXII), a depth that the Gītā and Vyāsa passages do not grade.",
        "extra_cites": [],
        "principle": {"id": "P2-standpoint", "reason": "The same restlessness is described as the mind's nature to be held by practice (BhG), as a ground of mind (YB), and as a hindrance to be known (MN 10)."},
        "pending_members": ["dx:gk-viksepa (GK 3.42–43 are cited in diagnosis.json but missing from data/)"],
    },
    {
        "id": "oc:samsaya-vicikiccha",
        "title": "saṃśaya ↔ vicikicchā",
        "members": [
            {"dx": "dx:antaraya-samsaya", "term": "saṃśaya (an antarāya)", "cites": ["tea:yoga-sutra:1.30", "tea:yoga-bhasya:1.30"]},
            {"dx": "dx:nivarana-vicikiccha", "term": "vicikicchā (a nīvaraṇa)", "cites": ["tea:satipatthana-sutta:mn10:36", "tea:mahasatipatthana-sutta:dn22:13"]},
            {"dx": "dx:fetter-vicikiccha", "term": "vicikicchā (one of the five lower fetters)", "cites": ["tea:visuddhimagga:22.p683"]},
        ],
        "what_is_shared": "Both lists count doubt as a block to practice: saṃśaya is among the nine obstacles (YS 1.30), and vicikicchā among the five hindrances (MN 10:36; DN 22:13).",
        "what_differs": "Vyāsa defines saṃśaya as cognition touching both alternatives, 'this may be so, it may not be so' (YB 1.30): a wavering about any object of knowledge. MN 10 names the hindrance without defining its object, and treats it as something to know as present, arising and abandoned (MN 10:36). The Yoga places doubt among the distractions of mind (YB 1.30). The sutta places it among the dhammas to be contemplated. The Visuddhimagga also counts doubt among the five lower fetters (Vism XXII); within the Buddhist lens the hindrance and the fetter are graded exact in diagnosis.json. The Yoga list has no fetter sense.",
        "extra_cites": [],
        "principle": {"id": "P2-standpoint", "reason": "One wavering, named in an analysis of distraction (YS) and in a contemplation of dhammas (MN 10)."},
        "pending_members": [],
    },
    {
        "id": "oc:pramada-pamada",
        "title": "pramāda (YS) ↔ pamāda ↔ pramāda (TS)",
        "members": [
            {"dx": "dx:antaraya-pramada", "term": "pramāda (an antarāya)", "cites": ["tea:yoga-sutra:1.30", "tea:yoga-bhasya:1.30"]},
            {"dx": "dx:pamada", "term": "pamāda (heedlessness)", "cites": ["tea:dhammapada:21"]},
            {"dx": "dx:jain-pramada", "term": "pramāda (a cause of bondage)", "cites": ["tea:tattvartha-sutra:8.1"]},
        ],
        "what_is_shared": "All three lenses name heedlessness. YS: it is not cultivating the means of samādhi (YB 1.30). Dhammapada: heedfulness is the path to the deathless, heedlessness the path to death (Dhp 21). TS: heedlessness (pramāda) is one of the five causes of bondage (TS 8.1). The Gītā also names pramāda among the bonds of tamas (BhG 14.8).",
        "what_differs": "The same word has three senses. In YS it is a lapse in practice, an obstacle among the distractions (YB 1.30). In the Dhammapada it is the opposite of the heedfulness that leads to the deathless (Dhp 21). In TS it is a cause of karmic bondage, beside wrong view, non-abstention, the passions and activity (TS 8.1). The Gītā makes it a mark of tamas, a strand of nature (BhG 14.8).",
        "extra_cites": ["tea:bhagavad-gita:14.8"],
        "principle": {"id": "P2-standpoint", "reason": "One failing, named from the standpoint of meditation (YS), of the path to the deathless (Dhp), and of karmic bondage (TS)."},
        "pending_members": [],
    },
    {
        "id": "oc:avirati",
        "title": "avirati (YS) ↔ avirati (TS)",
        "members": [
            {"dx": "dx:antaraya-avirati", "term": "avirati (an antarāya)", "cites": ["tea:yoga-sutra:1.30", "tea:yoga-bhasya:1.30"]},
            {"dx": "dx:jain-avirati", "term": "avirati (a cause of bondage)", "cites": ["tea:tattvartha-sutra:8.1", "tea:tattvartha-sutra:7.1"]},
        ],
        "what_is_shared": "Both lists use the word avirati, non-abstention, for something that keeps the practitioner distracted or bound (YS 1.30; TS 8.1).",
        "what_differs": "It is the same word with a different sense. For Vyāsa, avirati is greed (gardha) of the mind, which consists in contact with sense-objects (YB 1.30): a distraction in meditation. In TS it is the absence of the vows. Abstention (virati) from violence, falsehood, stealing, unchastity and possessiveness is the vow (TS 7.1), and non-abstention is a cause of bondage (TS 8.1). The Yoga's own counterpart to the Jain vows is not this obstacle but the restraints (yama): non-harming, truthfulness, non-stealing, continence and non-possessiveness (YS 2.30).",
        "extra_cites": ["tea:yoga-sutra:2.30"],
        "principle": {"id": "P2-standpoint", "reason": "The shared word is read within each system's own standpoint: the mind's greed for objects (YB) and the absence of vows (TS). The row does not merge the two senses."},
        "pending_members": [],
    },
    {
        "id": "oc:daurmanasya-visada-arta",
        "title": "daurmanasya ↔ viṣāda (Arjuna) ↔ ārta-dhyāna",
        "members": [
            {"dx": "dx:companion-daurmanasya", "term": "daurmanasya (a companion of distraction)", "cites": ["tea:yoga-sutra:1.31", "tea:yoga-bhasya:1.31"]},
            {"dx": "dx:gita-visada", "term": "viṣāda, kārpaṇya (Arjuna's dejection)", "cites": ["tea:bhagavad-gita:1.28", "tea:bhagavad-gita:2.1", "tea:bhagavad-gita:2.7"]},
            {"dx": "dx:jain-arta-dhyana", "term": "ārta-dhyāna (sorrowful dwelling)", "cites": ["tea:tattvartha-sutra:9.28", "tea:tattvartha-sutra:9.30-33"]},
        ],
        "what_is_shared": "Each names a sinking, sorrowful turn of mind. Vyāsa: dejection (daurmanasya) is a disturbance of the mind through the frustration of a wish, and it accompanies distraction (YS 1.31; YB 1.31). Gītā: Arjuna is overcome by pity and despairing (viṣīdan), his mind bewildered about dharma (BhG 1.28, 2.1, 2.7). TS: sorrowful dwelling (ārta-dhyāna) dwells on removing the disagreeable, on keeping the agreeable, on pain, and on longing for future enjoyment (TS 9.30–33). MN 10 declares the four establishments of mindfulness a path to the ending of pain and displeasure (dukkha-domanassa) (MN 10:2).",
        "what_differs": "(1) Daurmanasya in YS is a companion of distraction: it occurs in a distracted mind and is absent in a concentrated one (YB 1.31). (2) Arjuna's viṣāda is a crisis about dharma, and it becomes the occasion of the whole teaching (BhG 2.7). (3) Jain ārta-dhyāna is a kind of meditation (dhyāna), the inauspicious sorrowful one of four (TS 9.28): a sustained fixing of the mind, not a passing mood. This row describes states the texts name. It is not a finding about any person, and it makes no health claim.",
        "extra_cites": ["tea:satipatthana-sutta:mn10:2"],
        "principle": {"id": "P2-standpoint", "reason": "One sorrowful turn, seen as a companion of distraction (YB), as the occasion of teaching (BhG), and as an inauspicious kind of dwelling (TS)."},
        "pending_members": [],
    },
    {
        "id": "oc:vitarka-raudra",
        "title": "vitarka (hiṃsā and the rest) ↔ raudra-dhyāna",
        "members": [
            {"dx": "dx:vitarka-himsadi", "term": "vitarka (harmful thoughts)", "cites": ["tea:yoga-sutra:2.33", "tea:yoga-sutra:2.34", "tea:yoga-bhasya:2.34"]},
            {"dx": "dx:jain-raudra-dhyana", "term": "raudra-dhyāna (cruel dwelling)", "cites": ["tea:tattvartha-sutra:9.35", "tea:tattvartha-sutra:9.28"]},
        ],
        "what_is_shared": "Both name the mind dwelling on harming, falsehood, theft and possessions. YS: harmful thoughts (vitarka) such as violence, whether done, caused to be done or approved, and preceded by greed, anger or delusion, bear unending suffering and ignorance as their fruit, so one should cultivate their opposite (YS 2.33–34). TS: cruel dwelling (raudra-dhyāna) arises from violence, falsehood, theft and guarding one's objects (TS 9.35).",
        "what_differs": "YS vitarkas are thoughts that breach the restraints, and the remedy is to cultivate their opposite (pratipakṣa-bhāvanā, YS 2.33). The Jain raudra is one of four kinds of meditation (TS 9.28), an inauspicious sustained dwelling that TS places in the unrestrained and the partly restrained (TS 9.35). The Yoga states the fruit as suffering and ignorance (YS 2.34). The Jain account is of karmic bondage.",
        "extra_cites": [],
        "principle": {"id": "P2-standpoint", "reason": "The same harmful dwelling, seen as thoughts that breach the restraints (YS) and as an inauspicious kind of meditation (TS)."},
        "pending_members": [],
    },
    {
        "id": "oc:siddhi-upakkilesa-rasasvada",
        "title": "siddhi as upasarga ↔ vipassanūpakkilesa ↔ rasāsvāda",
        "members": [
            {"dx": "dx:siddhi-upasarga", "term": "siddhi as upasarga", "cites": ["tea:yoga-sutra:3.37", "tea:yoga-sutra:3.51"]},
            {"dx": "dx:vism-vipassanupakkilesa", "term": "vipassanūpakkilesa (imperfections of insight)", "cites": ["tea:visuddhimagga:20.p633", "tea:visuddhimagga:20.p637", "tea:visuddhimagga:20.p638"]},
            {"dx": "dx:gk-rasasvada", "term": "rasāsvāda (savouring the happiness)", "cites": ["tea:mandukya-karika:3.45"]},
        ],
        "what_is_shared": "Each warns that attainments or delights arising in practice can themselves become obstacles. YS: these perceptions are obstacles in samādhi and powers only for the outgoing mind (YS 3.37). Even when invited by the exalted, one should feel no attachment and no pride (YS 3.51). Visuddhimagga: when such states as knowledge, rapture, tranquillity and happiness arise, the meditator thinks 'surely I have reached the path' and takes what is not the path for the path (Vism XX). The one skilled in them regards them as 'this is not mine, I am not this, this is not my self' and does not waver (Vism XX). Gauḍapāda: one should not relish the happiness there, and through discernment one should be unattached (GK 3.45).",
        "what_differs": "(1) What arises: YS speaks of powers and extraordinary perceptions. The Visuddhimagga speaks of illumination, rapture, bliss and the rest arising in insight. Gauḍapāda speaks of the happiness of the stilled mind. (2) Why it obstructs: in YS they belong to the outgoing state (vyutthāna) and pull away from samādhi (YS 3.37). In the Visuddhimagga the error is mistaking them for the path. For Gauḍapāda it is relishing them. (3) In YS the same things are powers from one standpoint and obstacles from another (YS 3.37). The Upaniṣadic yoga texts differ on whether powers are signs or obstacles (see dsp:siddhis-sign-or-obstacle, which the ontology reconciles under P2 and where the Yogatattva's objection is recorded).",
        "extra_cites": [],
        "principle": {"id": "P2-standpoint", "reason": "YS 3.37 itself states the standpoint: obstacles in samādhi, powers in the outgoing state. The other two warnings are read in the same way, each from its own path."},
        "pending_members": [],
    },
    {
        "id": "oc:rajas-raga-carita",
        "title": "rajas ↔ rāga-carita",
        "members": [
            {"dx": "dx:guna-rajas", "term": "rajas (a guṇa)", "cites": ["tea:bhagavad-gita:14.7", "tea:bhagavad-gita:14.12"]},
            {"dx": "dx:carita-raga", "term": "rāga-carita (greedy temperament)", "cites": ["tea:visuddhimagga:3.p101/2"]},
        ],
        "what_is_shared": "Both read a person's make-up by what predominates in it, and both mark this predominance by greed. Gītā: rajas is of the nature of passion, springs from thirst and attachment, and shows as greed, activity, restlessness and craving (BhG 14.7, 14.12). Visuddhimagga: the greedy temperament (rāga-carita) is the first of six temperaments (Vism III).",
        "what_differs": "Rajas is a strand of prakṛti present in every being. It binds the embodied one (BhG 14.5), and one can go beyond the guṇas (BhG 14.20). The greedy temperament is a classification of persons, one of six (greedy, hating, deluded, faithful, intelligent, speculative), and the Visuddhimagga's account does not rest on prakṛti (Vism III). No reading of a guṇa or a temperament is a judgement about a person's worth or health.",
        "extra_cites": ["tea:bhagavad-gita:14.5", "tea:bhagavad-gita:14.20"],
        "principle": {"id": "P2-standpoint", "reason": "Predominance is analysed from a cosmic standpoint (a strand of nature, BhG) and from a practical one (a temperament, Vism). They overlap only where greed is named in both."},
        "pending_members": [],
    },
    {
        "id": "oc:tamas-moha-carita",
        "title": "tamas ↔ moha-carita",
        "members": [
            {"dx": "dx:guna-tamas", "term": "tamas (a guṇa)", "cites": ["tea:bhagavad-gita:14.8", "tea:bhagavad-gita:14.13"]},
            {"dx": "dx:carita-moha", "term": "moha-carita (deluded temperament)", "cites": ["tea:visuddhimagga:3.p101/2"]},
        ],
        "what_is_shared": "Both mark a predominance by delusion. Gītā: tamas is born of ignorance, deludes all embodied beings, and shows as darkness, inactivity, heedlessness and delusion (BhG 14.8, 14.13). Visuddhimagga: the deluded temperament (moha-carita) is one of six temperaments (Vism III).",
        "what_differs": "Tamas is a strand of prakṛti that binds the embodied one (BhG 14.5, 14.8), and one can go beyond the guṇas (BhG 14.20). The deluded temperament is a classification of persons, and the Visuddhimagga's account does not rest on prakṛti (Vism III). The Gītā has three guṇas, the Visuddhimagga six temperaments; sattva has no temperament counterpart. No reading of a guṇa or a temperament is a judgement about a person's worth or health.",
        "extra_cites": ["tea:bhagavad-gita:14.5", "tea:bhagavad-gita:14.20"],
        "principle": {"id": "P2-standpoint", "reason": "Predominance is analysed from a cosmic standpoint (a strand of nature, BhG) and from a practical one (a temperament, Vism). They overlap only where delusion is named in both."},
        "pending_members": [],
    },
    {
        "id": "oc:abhinivesa-bhavatanha",
        "title": "abhiniveśa ↔ bhava-taṇhā",
        "members": [
            {"dx": "dx:klesa-abhinivesa", "term": "abhiniveśa (clinging to life)", "cites": ["tea:yoga-sutra:2.9", "tea:yoga-bhasya:2.9"]},
            {"dx": "dx:tanha", "term": "taṇhā, including craving for being (bhava-taṇhā)", "cites": ["tea:mahasatipatthana-sutta:dn22:19"]},
        ],
        "what_is_shared": "Both name a wish to go on being. Vyāsa: in every living being there is the constant wish 'may I not cease to be; may I be' (YB 2.9), and it flows on by its own momentum even in the learned (YS 2.9). DN 22: craving includes craving for being, and it leads to renewed becoming (DN 22:19).",
        "what_differs": "(1) Vyāsa infers from this wish an experience of death in a previous birth (YB 2.9). DN 22 places craving for being inside the origin of suffering, alongside craving for sense pleasures and for non-being (DN 22:19), and the passage makes no such inference. (2) YS makes abhiniveśa one of five kleśas rooted in avidyā (YS 2.3–4). DN 22 makes all craving one origin. (3) The Yoga's end is the seer's aloneness (YS 2.25). DN 22's end is the cessation of craving (DN 22:20). Whether any self remains is the open question in row ot:provisional-self-question of one_truth.json.",
        "extra_cites": ["tea:yoga-sutra:2.3", "tea:yoga-sutra:2.4", "tea:yoga-sutra:2.25", "tea:mahasatipatthana-sutta:dn22:20"],
        "principle": {"id": "P2-standpoint", "reason": "One wish to go on being, analysed as a kleśa (YS) and as a form of the craving that is the origin of suffering (DN 22)."},
        "pending_members": [],
    },
]
