"""New cues for the diagnosis layer's markers (P3: recall of the offline rules engine).

NEW[entry id] = [(start of the marker text, [new cues]), ...]. Applied by add_cues.py to layers/diagnosis.json: each cue
is appended to that marker's "cues" and listed in its "cues_added". Cues only help the rules engine notice a marker
(SCHEMA.md); the marker text, from the sources, is what a mapping rests on. Every cue is first person, present or
habitual, everyday English, and says only what its marker says (practice-setting markers keep the practice setting).

Deliberately NOT given new cues (see the P3 report):
- attainment / goal states listed beside the obstacles, whose own not_to_be_read_as forbids telling a person they are
  in them: dx:gunatita, dx:gita-sthitaprajna, dx:gk-amanibhava, dx:katha-yoga-state, and both markers of
  dx:cittabhumi ("the product never tells a person which ground they are in");
- markers that can only be paraphrased in body, sleep or food words: the posture and eating markers of dx:carita-raga,
  dx:carita-dosa and dx:carita-moha; dx:jain-arta-dhyana "The mind fixed on pain (TS 9.32)".
"""

NEW = {'dx:klesa-asmita': [('Taking the mind that thinks',
                      ['I identify with my thoughts',
                       "I can't separate myself from my thoughts",
                       'when my opinions are criticised I feel attacked myself',
                       'my moods feel like my true self',
                       'an attack on my ideas feels like an attack on me',
                       'I identify completely with whatever my mind concludes'])],
 'dx:klesa-raga': [('Wanting a pleasure again',
                    ['I keep replaying it and wanting it again',
                     'remembering it makes me crave it',
                     'the memory of that pleasure pulls me back to it',
                     'I chase the feeling I had on that trip',
                     'I keep reliving the holiday',
                     'I miss that pleasure so much I plan to repeat it']),
                   ('Vyāsa: attachment seen toward one object',
                    ['a new craving replaces the last in me',
                     'my cravings just change objects',
                     'my attachment just shifts to a new object',
                     'I drop an attachment and find another waiting',
                     'each craving I satisfy is soon replaced by another'])],
 'dx:klesa-dvesa': [('Pushing against a pain',
                     ['I recoil from anything that reminds me of it',
                      'I avoid anything that reminds me of it',
                      'I push people away when I remember how they hurt me',
                      'I still resent them for how they hurt me',
                      'the old hurt makes me hostile to anything like it',
                      'I resent anything that brings back that humiliation'])],
 'dx:klesa-abhinivesa': [("The wish 'may I not cease to be",
                          ['I dread the idea of ceasing to exist',
                           'my own death frightens me',
                           'a dread of dying grips me on ordinary days',
                           'I cling to going on existing whatever happens',
                           'I fear my own death more than anything',
                           'the thought of not existing terrifies me'])],
 'dx:antaraya-styana': [('The mind will not take up the work',
                         ['my mind is unfit for effort at prayer',
                          'my mind feels unfit for the effort of meditation',
                          'my mind refuses to engage with my studies',
                          'my mind is rigid and unworkable at practice time',
                          'I face my practice and my mind does not budge'])],
 'dx:antaraya-samsaya': [('Knowing that touches both sides',
                          ['I doubt this spiritual path',
                           'I doubt the teachings',
                           'I waver between believing the teaching and doubting it',
                           'I doubt whether this spiritual path is true',
                           'I doubt whether my practice leads anywhere',
                           "I stall in my practice because I'm unsure it's true",
                           'my mind swings to and fro about the teachings'])],
 'dx:antaraya-pramada': [('Not doing the practice one knows',
                          ['I keep neglecting my prayers',
                           'I keep neglecting my meditation',
                           'I keep skipping my practice',
                           'I keep postponing my practice',
                           'my practice keeps lapsing',
                           'my chanting goes undone',
                           'I skip the practice I know supports my progress',
                           "I've been meaning to start a practice"])],
 'dx:antaraya-alasya': [('Not starting, because body and mind',
                         ['I feel leaden and weighed down at practice time',
                          "I'm weighed down at prayer time",
                          "I drag my feet and don't start my meditation",
                          'an inertia keeps me from my study',
                          'sloth keeps me from my chanting',
                          'I drag my feet over starting my prayers'])],
 'dx:antaraya-avirati': [("The mind's greed for contact",
                          ["I can't turn away from pleasant distractions",
                           'my mind reaches greedily for every pleasant thing',
                           'my greed for pleasant things keeps me from practising',
                           'I stay hooked on anything that pleases my senses',
                           'the pull of pleasant things beats my wish to practise',
                           'my greed for pleasures keeps winning'])],
 'dx:antaraya-bhranti-darsana': [('Seeing wrongly, as when one moon',
                                  ['I misread the signs in my practice',
                                   'I take mistaken ideas about meditation as the truth',
                                   'I keep getting the teaching backwards and acting on it',
                                   "I feel certain about my practice and then find I'm mistaken"])],
 'dx:antaraya-alabdha-bhumikatva': [('Not reaching any settled ground',
                                     ['I practise daily and never reach steady ground',
                                      'my practice stays at the same shallow level',
                                      'I never get beyond the first stage of meditation',
                                      'my meditation never deepens into any settled stage'])],
 'dx:antaraya-anavasthitatva': [('Losing a ground once gained',
                                 ['the steadiness I gain in practice keeps slipping away',
                                  'I keep losing the ground I gained in meditation',
                                  'each time I get steady in prayer I slide back',
                                  'the progress I make in meditation keeps slipping away',
                                  'I lose my footing in practice after a good spell'])],
 'dx:companion-daurmanasya': [('The mind shaken because a wish',
                               ['I get upset and rattled whenever my wishes are thwarted',
                                'a thwarted plan leaves me agitated',
                                "I'm disturbed for days when a wish of mine is refused",
                                "my mind gets churned up when I don't get my way",
                                "when my plans are thwarted I'm shaken",
                                'a blocked wish shakes me'])],
 'dx:vitarka-himsadi': [('Thoughts of harming, lying, stealing',
                         ['I keep plotting revenge on them',
                          "I'm tempted to lie to get out of trouble",
                          "I'm tempted to steal",
                          'the thought of stealing small things tempts me',
                          'I approve when others harm the people I dislike',
                          'I approve of harm done on my behalf',
                          'I rehearse hitting back at them in my head'])],
 'dx:guna-sattva': [('When light, knowledge, arises',
                     ['my understanding feels lit up',
                      'a brightness of knowing fills me through the day',
                      'my perception feels luminous and alert',
                      'my senses feel luminous']),
                    ('The sāttvika doer',
                     ['I work with zeal and stay unmoved by success or failure',
                      'success and failure leave me equally steady',
                      "I don't boast about the good work I do",
                      'I act with steady enthusiasm and no attachment to the outcome']),
                    ('Sāttvika happiness',
                     ['the discipline felt like a burden at first and now brings me deep joy',
                      'my practice began as a struggle and has turned into a quiet joy',
                      'my joy is born of my own understanding',
                      'my early effort was grim and the reward is a clear mind'])],
 'dx:guna-rajas': [('When rajas grows',
                    ['I cram my days with undertakings',
                     'I pile project upon project',
                     'a restless longing drives me from task to task',
                     'my greed for more keeps me constantly on the go',
                     "I can't sit idle"]),
                   ('The rājasa doer',
                    ["I'm eager for the payoff more than the work itself",
                     "I'm elated by success and crushed by failure",
                     'I chase results greedily and push others aside',
                     "I'm swept between joy and grief by how my work turns out",
                     'I measure my effort only by the gain']),
                   ('Rājasa happiness',
                    ['the thrill fades and leaves me empty',
                     'every pleasure I chase turns to regret in the end',
                     'my excitement over buying something fades into regret',
                     'sense pleasures delight me and then disappoint me'])],
 'dx:guna-tamas': [('When tamas grows',
                    ['my mind is dark and inert',
                     'I sit around in a fog and ignore my duties',
                     'my mind is clouded and I let everything slide',
                     "I'm inactive and careless about my duties"]),
                   ('The tāmasa doer',
                    ['I procrastinate for weeks',
                     'I keep telling myself tomorrow',
                     "I've been meaning to start for months",
                     "I'm stubborn and refuse to change how I do things",
                     'I delay and delay until the deadline has passed',
                     'I procrastinate and sink into gloom',
                     'I postpone important things endlessly']),
                   ('Tāmasa steadiness',
                    ['I hold on stubbornly to my grief and my pride',
                     'I refuse to let go of old fears and gloom',
                     'I find my pleasure in lazing about and forgetting everything',
                     'I hang on to my despondency day after day'])],
 'dx:gita-anger-chain': [('Turning an object over and over',
                          ['the more I dwell on it, the more I want it',
                           'I turn it over and over until I crave it',
                           'brooding on something I saw turns into desire for it',
                           'I dwell on the thing I saw until I have to have it']),
                         ('Anger born of desire, then clouding',
                          ['my anger clouds my judgement completely',
                           'in my anger I forget everything I have learned',
                           'in anger my good sense deserts me',
                           'thwarted desire turns into rage that makes me lose my head'])],
 'dx:gita-kama-krodha': [("Acting wrongly against one's own wish",
                          ['I act against my own better judgement, pushed by some force',
                           'I break my own resolutions again and again',
                           'something drives me into wrongdoing against my wishes',
                           'I give in and act wrongly against my own wishes']),
                         ('A fire that cannot be filled',
                          ['my wanting is never satisfied',
                           'my craving burns like a fire that is never full',
                           'my desire hides what I know like a fog',
                           'my desire blinds me to what I understand']),
                         ('The surge (vega)',
                          ['a surge of wanting rises in me and I strain to hold it',
                           'a rush of anger surges through me before I can think',
                           'the urge of desire and anger sweeps over me',
                           'I feel a wave of anger rising and struggle to bear it'])],
 'dx:gita-asuri-sampad': [('Hypocrisy, arrogance, conceit',
                           ['I act pious in public and behave differently at home',
                            'I speak harshly to people I consider beneath me',
                            "I'm arrogant and conceited at work",
                            'I flaunt my goodness so people admire me',
                            "I'm harsh and conceited with those under me"])],
 'dx:gita-visada': [('Sinking before a duty',
                     ['I sink at the thought of the duty in front of me',
                      "I'm torn about my duty",
                      'I collapse inside before a task that feels unbearable',
                      'I lose heart facing my obligations']),
                    ('The body giving way with the mind whirling',
                     ['my mind whirls when I face my duty',
                      'my mind reels before the duty in front of me',
                      'everything spins inside me before that duty',
                      'my thoughts whirl before the task ahead']),
                    ('Turning to a teacher',
                     ["I'm searching for a guru to teach me",
                      'I long for someone wise to guide me',
                      "I'm begging someone wise to teach me",
                      'I have come to the point of begging for guidance'])],
 'dx:gita-restless-mind': [('The mind moving off wherever it will',
                            ['my mind wanders off',
                             'my mind keeps drifting off',
                             'my thoughts run off',
                             'my thoughts wander to errands and emails',
                             'my mind jumps about restlessly',
                             'my mind darts off in every direction',
                             'my mind is restless and unsteady']),
                           ('The senses dragging the mind',
                            ['whatever catches my eye drags my mind after it',
                             'a sound or a screen pulls my mind away instantly',
                             'passing sights drag my attention off',
                             'my senses drag me after every distraction'])],
 'dx:gk-laya': [('In stilling the mind, sinking',
                 ['when I meditate I sink into a cosy blankness',
                  'my meditation sinks into a pleasant fog',
                  'in meditation my mind goes blank and dull',
                  'during my practice I slip into a comfortable blank',
                  'at prayer I sink into a warm dullness',
                  'I sink into a blank when I meditate'])],
 'dx:gk-viksepa': [('The mind running out among desires',
                    ['my mind chases pleasures when I try to be still',
                     'my thoughts scatter toward pleasures when I meditate',
                     'in stillness my mind scatters among desires',
                     'my stillness scatters into daydreams of pleasure'])],
 'dx:gk-kasaya': [('The mind neither sunk nor scattered',
                   ["in meditation I'm calm with a subtle tint of wanting underneath",
                    'my stillness is tinged with old desires',
                    "I'm settled in practice with a hidden pull underneath",
                    'my meditative calm is coloured by a hidden residue'])],
 'dx:gk-rasasvada': [('Enjoying the happiness of stillness',
                      ['I linger in the bliss of meditation and go no further',
                       'I savour the bliss of stillness and cling to it',
                       'I relish the peace of my practice and go no deeper',
                       "I'm hooked on the blissful feeling I get in meditation",
                       'I cling to the bliss of meditation'])],
 'dx:gk-asparsa-fear': [('Drawing back in fear',
                         ['fear stops me as my meditation deepens',
                          'deep stillness in meditation frightens me',
                          "I'm afraid of losing myself when meditation goes deep",
                          'I back away from the inner silence out of fear',
                          'fear of vanishing makes me stop when I meditate'])],
 'dx:katha-unrestrained-senses': [('The senses running like vicious horses',
                                   ['my senses bolt like wild horses',
                                    "my good sense can't rein in my cravings",
                                    'my desires drag me wherever they please',
                                    'I have no control over my senses',
                                    'I have no grip on the reins of my mind']),
                                  ('Going round without arriving',
                                   ['I go round and round on my spiritual path without arriving',
                                    'my practice keeps circling without arriving',
                                    'my spiritual search keeps returning to where it began',
                                    'my spiritual search goes round in circles'])],
 'dx:katha-outward-senses': [('Looking always outward',
                              ['I never look within',
                               'my gaze is fixed outward on people and things',
                               'my attention is always outside me, never inward',
                               'I never turn my gaze inward']),
                             ('Following outward desires',
                              ['I run after outward desires',
                               'I chase every new desire',
                               'I move from purchase to purchase',
                               'my days are an endless string of outside pursuits'])],
 'dx:katha-preyas': [('Choosing what is pleasant now',
                      ['I choose pleasure over my own good',
                       'I choose comfort over growth',
                       'I trade long-term good for pleasure now',
                       'I reach for the pleasant thing and skip what is beneficial',
                       'I choose the fun option over the worthwhile',
                       'I grab pleasure now and let the good slide']),
                     ('Thinking oneself wise',
                      ['I consider myself wise and repeat the same mistakes',
                       'I pride myself on knowing and stay ignorant',
                       "I'm certain I understand and end up where I began",
                       'I act the expert and stay blind to my ignorance'])],
 'dx:nivarana-kamacchanda': [('The mind lured by sensual desire',
                              ['my mind is lured by pleasures when I meditate',
                               'tempting thoughts keep luring my mind off the mantra',
                               'desire keeps my mind from settling on its object',
                               'desire for pleasant things pulls my attention from the prayer',
                               'sensual thoughts keep drawing me off my meditation',
                               'longing for pleasures scatters my focus in meditation'])],
 'dx:nivarana-byapada': [('Hindered by ill will toward the object',
                          ['irritation at the noise breaks up my meditation',
                           'resentment keeps breaking my concentration in prayer',
                           'my prayer keeps snagging on people I dislike',
                           'my meditation is broken by hostile thoughts about someone',
                           'in meditation my mind keeps bristling at people I dislike']),
                         ("'He abused me, he struck me",
                          ['I dwell on the insult',
                           'I replay the insult over and over for days',
                           'I brood over how I was wronged',
                           'I keep going over how badly they treated me',
                           'I relive the argument in my head for weeks',
                           'I cling to the grievance'])],
 'dx:nivarana-thina-middha': [('Overcome by stiffness and torpor',
                               ['my mind is stiff and dull in meditation',
                                'torpor and stiffness grip me at prayer',
                                'my mind is rigid and unwieldy when I study',
                                'my mind stiffens and drags during chanting',
                                  'my mind goes dull and foggy when I meditate']),
                              ('Sinking, drooping',
                               ['during meditation I droop and sink lower and lower',
                                'halfway through my prayers I droop and stretch lazily',
                                'my head droops while I recite the mantra',
                                'I sink into boredom when I study'])],
 'dx:nivarana-uddhacca-kukkucca': [('Seized by restlessness and remorse',
                                    ["my mind flits about restlessly and can't rest",
                                     'restless thoughts and regrets churn in me when I sit to pray',
                                     "I'm agitated inside and my mind hops from worry to worry",
                                     'my mind is unsettled and jittery',
                                     'my mind is restless and unpeaceful']),
                                   ('Regret afterwards',
                                    ['I keep going over my old mistakes',
                                     'I torment myself over things I left undone',
                                     'I keep reliving my mistakes and feeling ashamed',
                                     "I'm consumed by regret over how I behaved",
                                     'I keep replaying conversations and regretting my words',
                                     'I keep regretting things I said',
                                     "I keep regretting what I didn't say"]),
                                   ('DN 2: while the five hindrances',
                                    ['my regrets rule me like a master rules a servant',
                                     "I'm a slave to my restless thoughts",
                                     'my remorse holds me captive',
                                     "I'm at the beck and call of my worries"])],
 'dx:nivarana-vicikiccha': [('Stricken by doubt',
                             ['doubt about the method stops me from really practising',
                              'my doubts about the teaching keep me from practising',
                              'doubt keeps me from committing to any practice',
                              'I stand at the edge of the practice, stuck in doubt']),
                            ('Wavering, taking now one side',
                             ['I keep switching spiritual teachers',
                              'I keep switching traditions',
                              'I flip from trusting the teaching to dismissing it',
                              "I'm torn between two spiritual paths and keep changing sides",
                              'I trust the spiritual path and then doubt it',
                              'I keep wavering over practices'])],
 'dx:fetter-vicikiccha': [('Wavering, taking now one side',
                           ['I waver about the spiritual path',
                            'I keep doubting whether the teaching is true',
                            'I keep switching sides about the spiritual path I follow',
                            'I trust the teaching and then doubt it',
                            'my faith in the practice swings from side to side'])],
 'dx:fetter-silabbata-paramasa': [('Holding that keeping a rule',
                                   ['I believe the ritual alone makes me pure',
                                    'I count on my observances to purify me by themselves',
                                    'I trust that keeping the vows perfectly is what frees me',
                                    "I'm convinced the correct ritual is all that matters",
                                    'I rely on the rules themselves to make me pure'])],
 'dx:fetter-kamaraga': [('Greed that sticks to its object',
                         ["my desire sticks to it and won't let go",
                          'I stay stuck on wanting that pleasure',
                          'the craving grips me and refuses to let go',
                          'I cling to that pleasure like glue'])],
 'dx:fetter-patigha': [('Ferocity toward its object',
                        ['my resentment spreads like poison through the day',
                         'I turn fierce toward anyone who crosses me',
                         'my anger at one person spills over onto others',
                         'I flare up with fierce hostility toward them'])],
 'dx:fetter-mana': [('Holding oneself high',
                     ['I secretly rank myself above my colleagues',
                      'I want my achievements to be seen and praised',
                      'I rate myself above others',
                      'I show off to be admired',
                      'I seethe when others get the credit I deserve',
                      'I seethe when I go unnoticed',
                      "I'm better than the others"])],
 'dx:fetter-uddhacca': [('Disquiet, like water whipped by wind',
                         ['my mind is choppy and whipped up',
                          'a disquiet keeps stirring in me',
                          'my thoughts are churned up',
                          "I'm stirred up and agitated inside even at rest"])],
 'dx:root-lobha': [('Grasping that sticks and will not let go',
                    ["I grip tightly to what I own and can't part with it",
                     'I hoard things and refuse to give them up',
                     "I cling to my possessions and can't let them go",
                     'my grasping sticks to anything I get',
                     'I refuse to let it go',
                     "when it's threatened I fight to keep it",
                     "I can't let go of my house"]),
                   ('There is no fire like lust',
                    ['my greed burns in me like a fire',
                     'a burning desire for more consumes me',
                     'my craving flares up hotter than anything',
                     'the fire of wanting keeps burning in me'])],
 'dx:root-dosa': [('Ferocity that spreads and burns',
                   ["my rage hurts me more than the one it's aimed at",
                    'my anger burns inside me for days',
                    'my fury spreads and scorches me first',
                    'my hostility burns me up from inside']),
                  ('Hatred is never appeased by hatred',
                   ['I answer hostility with hostility',
                    'I hate people in return when they are cruel to me',
                    'I meet their hatred with more hatred of my own',
                    'I keep stoking my hatred of them'])],
 'dx:root-moha': [('Blindness of mind',
                   ['my mind is clouded and blind to things',
                    'I stay blind to the true nature of things',
                    'a fog over my mind hides how things truly are',
                    'confusion hides the real state of things from me']),
                  ('There is no net like delusion',
                   ["I'm tangled in my own confusion",
                    "I'm caught in a net of wrong ideas",
                    "my confusion traps me and I can't find the way out",
                    'my thinking is caught in a web of muddle'])],
 'dx:tanha': [('Delighting now here, now there',
               ['I delight in one thing and then crave the next',
                'my craving moves from pleasure to pleasure',
                'my wanting hops from delight to delight',
                'I get attached to anything that pleases me']),
              ('Growing like a creeper',
               ["my craving spreads like a creeper when I'm careless",
                "my wanting grows fastest when I'm careless",
                'my cravings creep further into my days unnoticed',
                'my unwatched cravings keep spreading'])],
 'dx:pamada': [('Letting life slip by',
                ['I drift through my days neglecting the important things',
                 'I waste my days on trivial things',
                 'I let the months slip by unused',
                 'I fritter away my time and neglect what counts',
                 "I'm careless with my days"])],
 'dx:mutthassati': [('Mindfulness muddled',
                     ['I go through my day on autopilot',
                      'I do whole tasks with my mind elsewhere',
                      'my awareness is muddled and I do things blindly',
                      "I'm only half present in whatever I'm doing"])],
 'dx:citta-sankhitta': [("The text names the state and asks only that it be known as it is: 'he knows a contracted",
                         ['my mind feels contracted and withdrawn',
                          'my mind narrows and shrinks into itself',
                          'my mind has shrunk into a small tight space',
                          'my mind is shut up and withdrawn'])],
 'dx:citta-vikkhitta': [("The text names the state and asks only that it be known as it is: 'he knows a scattered",
                         ['my mind is scattered in a dozen directions',
                          'my thoughts are strewn everywhere',
                          'my mind is in pieces, pulled in all directions',
                          'my attention is split and scattered'])],
 'dx:carita-raga': [('Work: sweeps carefully',
                     ['I do my work carefully, evenly and gracefully',
                      'my work is gentle, skilful and even',
                      'I tidy so evenly it looks like arranging flowers',
                      'I sweep and tidy with a light, even touch']),
                    ('Seeing: looks long',
                     ['I gaze at lovely things in amazement',
                      'I fasten on small virtues and overlook real faults',
                      'I linger over a beautiful sight and leave reluctantly',
                      "I overlook people's real flaws"]),
                    ('States that often occur: deceit, fraud',
                     ["I'm vain and keen to be admired",
                      "my wishes are big and I'm fickle about them",
                      "I'm discontented and always after something grander",
                      'I bend the truth to look good'])],
 'dx:carita-dosa': [('Work: grips the broom tightly',
                     ['my work is tense, stiff and uneven',
                      'I grip my tools tightly and bang about noisily',
                      'I clean in a harsh rush and make a mess',
                      'I do tasks roughly and hastily']),
                    ('Seeing: does not look long',
                     ['I pick on small faults and ignore the good',
                      'I spot every little flaw and dismiss real merits',
                      'I leave without a backward glance',
                      'I discount real virtues']),
                    ('States that often occur: anger, resentment',
                     ['I look down on people with contempt',
                      "I'm envious when a colleague is praised",
                      'I begrudge sharing what I have',
                      'resentment smoulders in me for weeks'])],
 'dx:carita-moha': [('Work: holds the broom loosely',
                     ['my work is muddled and undecided',
                      'I fumble about and do jobs unevenly',
                      'I switch this way and that and the job comes out messy',
                      'I go about tasks loosely and without skill']),
                    ('Seeing: depends on others',
                     ['I praise what others praise and blame what they blame',
                      'I echo the opinions of people around me',
                      "I'm indifferent and borrow my views from others",
                      'I take my likes and dislikes from the crowd']),
                    ('States that often occur: stiffness',
                     ['I hold on to my opinions tenaciously',
                      "I'm stubborn and refuse to let go of my ideas",
                      "I'm torn by doubt and regret most days",
                      "I'm dull and restless by turns"])],
 'dx:carita-saddha': [('Posture, work, eating and seeing: like the greedy',
                       ['I handle my tasks gently and evenly',
                        'I linger over lovely sights and leave them reluctantly',
                        "I dwell on people's small virtues",
                        'I arrange things neatly and pleasingly']),
                      ('States that often occur: generosity',
                       ["I'm openhanded and generous",
                        'I seek out holy people',
                        'I trust readily where trust is deserved',
                        "I'm guileless and glad at heart",
                        "I'm drawn to hearing the true teaching"])],
 'dx:carita-buddhi': [('Posture, work, eating and seeing: like the hating',
                       ['I work briskly and firmly',
                        'I spot faults quickly and move on',
                        "I don't linger over pleasant sights",
                        'my work is brisk and firm']),
                      ('States that often occur: being easy to correct',
                       ['I accept correction easily and change course',
                        'I seek out wise friends and heed their advice',
                        'a sense of urgency stirs me to strive',
                        'seeing how fleeting things are, I strive harder'])],
 'dx:carita-vitakka': [('Posture, work, eating and seeing: like the deluded',
                        ['my work is muddled and I leave it unfinished',
                         "I echo other people's praise and blame",
                         'I handle my tasks loosely and unevenly',
                         'my opinions depend on whoever I last spoke to']),
                       ('States that often occur: much talking',
                        ['I chatter endlessly and crave company',
                         'I scheme by night and rush about by day',
                         'I dislike steady good habits and drift between projects',
                         'I love company and find quiet devotion dull'])],
 'dx:vism-palibodha': [('Ties that take up the time and mind',
                        ['family obligations crowd out my meditation',
                         'renovating the house crowds out my meditation',
                         'constant travel keeps interrupting my meditation',
                         'worry about money pulls my mind away from practice',
                         'managing my property crowds out my prayers'])],
 'dx:vism-vipassanupakkilesa': [('Taking lights, joy, calm',
                                 ['the calm in my meditation convinces me I have arrived',
                                  'I take the joy I feel when meditating as proof of success',
                                  'I settle into the bright experiences as the goal itself',
                                  "I take the lights in meditation as a sign I've arrived"])],
 'dx:vism-brahmavihara-enemies': [('Kindness sliding into attachment',
                                   ['my kindness turns possessive',
                                    'my compassion drowns me in their sorrow',
                                    'my affection has become possessive',
                                    'my sympathy turns into my own grief',
                                    'my joy for others slides into chasing my own pleasures',
                                    'my calm has become plain indifference'])],
 'dx:kasaya-krodha': [('Anger, one of the four passions',
                       ["I'm angry for days",
                        'I snap at people over small things',
                        "my temper flares and I say things that aren't true",
                        'in anger I exaggerate and twist the facts',
                        'I lose my temper at the slightest delay',
                        'I shout in anger and say hurtful things',
                        'I fume about it for hours',
                        'I snap at whoever speaks to me'])],
 'dx:kasaya-mana': [('Pride, one of the four passions',
                     ["I'm too proud to apologise",
                      "I bristle when I'm overlooked",
                      "I can't bear being corrected by someone junior",
                      'I rank myself above the people I work with',
                      'my pride is wounded when someone else is praised',
                      'I refuse to bow to anyone',
                      "I tell myself they don't deserve it"])],
 'dx:kasaya-maya': [('Deceit, crookedness',
                     ['I hide my real intentions from people',
                      'I tell lies to cover my tracks',
                      'I show a false face at work',
                      'I pretend to agree and then go my own way',
                      'I twist the truth to get my way',
                      'I smile and agree in meetings and then say the opposite',
                      'I hide my real wishes from my family'])],
 'dx:kasaya-lobha': [('Greed, one of the four passions',
                      ["I hoard money and can't bear to part with it",
                       "I'm greedy for more money and things",
                       'I grab for more even when I have plenty',
                       "I'm stingy and hate to share what's mine",
                       'my greed makes me bend the truth'])],
 'dx:jain-nokasaya': [('Laughter, liking, disliking',
                       ['disgust rises in me at the sight of certain people',
                        'grief comes over me without warning',
                        'fear grips me in ordinary moments',
                        'I burst out laughing at the wrong moments',
                        "I'm swept by likes and dislikes all day"])],
 'dx:jain-avirati': [('Not holding back from harming',
                      ["I've taken no vow to refrain from harming",
                       'I tell lies freely',
                       "I take others' belongings freely",
                       "I don't restrain myself from harming or lying"])],
 'dx:jain-arta-dhyana': [('The mind fixed again and again on getting rid',
                          ['I keep scheming how to get away from what I dislike',
                           'I fixate on escaping the unpleasant job',
                           'I brood over how to be rid of what annoys me',
                           'I keep scheming to be rid of this unpleasant company']),
                         ('The mind fixed on getting back',
                          ['my mind fixes on regaining the comfort I had',
                           "I dwell on regaining the good times I've lost",
                           'I keep plotting to recover the pleasure I lost',
                           'I pine for my old comforts and scheme to regain them']),
                         ('The mind fixed on future enjoyments',
                          ['I daydream constantly about the pleasures ahead',
                           'my mind fixes on the enjoyments I have lined up',
                           'I fantasise about future pleasures all the time',
                           "I scheme about the luxuries I'm going to buy"])],
 'dx:jain-raudra-dhyana': [('The mind dwelling on harming',
                            ['I keep plotting how to hurt the people who crossed me',
                             'I dwell with relish on getting back at them',
                             'I work out elaborate lies to protect myself',
                             'I brood with pleasure on taking revenge',
                             'I fiercely guard my things and plan how to punish thieves'])]}

# ---------------------------------------------------------------------------------------------------------------------
# P6 (recall on realistic intake answers): everyday phrasings of each marker's own described sense, found missing on
# the dev set tests/fixtures/dev_personas.jsonl (layers/_gen/diagnosis/dev_recall.py). Same rules as above: first
# person, present or habitual, no clinical / body / food / sleep words, no tradition terms, no hypotheticals, and never
# wider than the marker. Prefixes are the same strings as in NEW, so each marker keeps a single spec (add_cues.py lists
# one "cues_added" per marker). dev_recall.py strips these to measure "before".
# ---------------------------------------------------------------------------------------------------------------------
NEW_P6 = {
 'dx:kasaya-krodha': [('Anger, one of the four passions',
                       ['I lose my temper',
                        "I'm mad for days",
                        'little things set me off',
                        'small things make me angry',
                        'I blow up in anger',
                        "I'm still fuming about it",
                        'I snap at my family',
                        'I have a short temper',
                        'I get furious over small things',
                        'I stay angry for hours'])],
 'dx:klesa-dvesa': [('Pushing against a pain',
                     ["I'm still angry about what they did",
                      'I still resent them',
                      "I still can't forgive them",
                      "I can't forgive and forget",
                      'I avoid them because of how they hurt me'])],
 'dx:nivarana-byapada': [("'He abused me, he struck me",
                          ['I hold grudges for years',
                           'I keep thinking about how they treated me',
                           'I keep arguing with them in my head',
                           'I replay the fight over and over',
                           'I keep thinking about how they cheated me',
                           'I never forget a wrong done to me',
                           "I'm still angry at them years later",
                           'I dwell on how they disrespected me'])],
 'dx:fetter-patigha': [('Ferocity toward its object',
                        ['I take my anger out on them',
                         'my anger spoils my whole day',
                         'my anger ruins my day'])],
 'dx:root-dosa': [('Ferocity that spreads and burns',
                   ["I'm boiling inside",
                    'I seethe inside for days',
                    'my anger keeps simmering inside me'])],
 'dx:carita-dosa': [('States that often occur: anger, resentment',
                     ["I'm jealous of my friends' success",
                      'I resent their success',
                      "I'm jealous when others succeed",
                      'I envy my friends',
                      'I compare myself and feel envious'])],
 'dx:gita-restless-mind': [('The mind moving off wherever it will',
                            ['my mind goes everywhere',
                             'my mind jumps around',
                             'my mind runs here and there',
                             'my thoughts jump around',
                             'I lose focus within minutes',
                             'I struggle to focus',
                             'I struggle to stay focused',
                             "I can't concentrate on my studies",
                             "I can't focus when I pray",
                             'I keep pulling my mind back',
                             'I have a monkey mind',
                             'my attention jumps from one thing to another',
                             'my mind goes somewhere else']),
                           ('The senses dragging the mind',
                            ['I keep checking my phone',
                             'my phone keeps pulling me away',
                             'every notification pulls me away'])],
 'dx:citta-vikkhitta': [("The text names the state and asks only that it be known as it is: 'he knows a scattered",
                         ['my mind is all over the place',
                          'my thoughts are all over the place',
                          'my mind is scattered',
                          'my mind is pulled in ten directions'])],
 'dx:nivarana-uddhacca-kukkucca': [('Seized by restlessness and remorse',
                                    ['my mind keeps racing',
                                     'my thoughts keep racing',
                                     "my mind won't switch off",
                                     'my mind never stops',
                                     'my thoughts keep spinning',
                                     'my mind never shuts up']),
                                   ('Regret afterwards',
                                    ['I keep thinking about my mistakes',
                                     'I replay my mistakes over and over',
                                     'I dwell on the past',
                                     'I keep thinking about the past',
                                     'my mind keeps going back to the past',
                                     'I regret the choices I made',
                                     'the guilt never leaves me',
                                     'I carry the guilt every day',
                                     'I blame myself for what happened',
                                     'I beat myself up over my mistakes',
                                     'my mistakes haunt me',
                                     'the past haunts me',
                                     "I'm full of regrets",
                                     'I regret the years I wasted',
                                     'I feel guilty about my mistakes'])],
 'dx:nivarana-vicikiccha': [('Wavering, taking now one side',
                             ["I don't know what to believe",
                              'I waver about what I believe',
                              'I keep switching practices',
                              'I jump from one practice to another',
                              'I keep moving between traditions',
                              'I doubt my teacher',
                              "I'm torn about my faith"])],
 'dx:fetter-vicikiccha': [('Wavering, taking now one side',
                           ["I don't know what to believe",
                            'I waver about what I believe',
                            'I keep switching practices'])],
 'dx:antaraya-samsaya': [('Knowing that touches both sides',
                          ['I doubt the practice',
                           'I keep wondering whether this practice is right',
                           'the doubt creeps into my practice',
                           'I question whether my prayers work'])],
 'dx:kasaya-mana': [('Pride, one of the four passions',
                     ['I feel superior to others',
                      "I'm smarter than my colleagues",
                      "I'm the smartest person in the room",
                      'I hate being corrected',
                      'I hate being questioned',
                      'I never admit I am wrong',
                      'I hate admitting I am wrong',
                      "I'm too proud to ask",
                      'it hurts my ego',
                      'my ego gets hurt easily'])],
 'dx:fetter-mana': [('Holding oneself high',
                     ['I deserve the credit',
                      'I crave recognition',
                      'I need to be admired',
                      'I show off my achievements',
                      'I feel superior to others'])],
 'dx:gita-asuri-sampad': [('Hypocrisy, arrogance, conceit',
                           ['I pretend to be religious',
                            'I act humble to look good',
                            'I act religious in front of my family'])],
 'dx:kasaya-maya': [('Deceit, crookedness',
                     ['I hide what I really think',
                      'I hide my true feelings',
                      'I pretend to be happy',
                      'I put on a fake smile',
                      'I tell people what they want to hear',
                      'I lie to my family',
                      'I keep lying to my parents',
                      'I cover up my mistakes',
                      'I keep secrets from my family',
                      'I lead a double life',
                      'I show a different face to different people',
                      'I talk behind their backs'])],
 'dx:guna-tamas': [('When tamas grows',
                    ['I lie on the couch doing nothing']),
                   ('The tāmasa doer',
                    ['I put things off until the last minute',
                     'I leave everything to the last minute',
                     'I keep postponing important things',
                     'I procrastinate every day',
                     "I can't bring myself to start",
                     'I always say tomorrow',
                     'I keep delaying what matters',
                     'I do something easier first',
                     'I avoid the task until the deadline'])],
 'dx:antaraya-alasya': [('Not starting, because body and mind',
                         ['laziness keeps me from starting',
                          'laziness keeps me from beginning'])],
 'dx:pamada': [('Letting life slip by',
                ['I waste hours on my phone',
                 'I waste hours scrolling',
                 'I waste my evenings on videos',
                 'my days slip away'])],
 'dx:antaraya-pramada': [('Not doing the practice one knows',
                          ['I keep putting off my practice',
                           'I keep putting off my meditation',
                           'I keep putting off my prayers',
                           "I've been meaning to meditate for months"])],
 'dx:nivarana-thina-middha': [('Overcome by stiffness and torpor',
                               ['my mind feels foggy',
                                'my mind is slow and dull',
                                'my mind goes blank when I study',
                                'my mind is in a fog',
                                'I feel foggy and slow']),
                              ('Sinking, drooping',
                               ['I get bored within minutes of studying'])],
 'dx:gk-laya': [('In stilling the mind, sinking',
                 ['a fog comes over me when I meditate'])],
 'dx:antaraya-styana': [('The mind will not take up the work',
                         ['my mind shuts down when I study',
                          'my mind refuses to cooperate when I pray'])],
 'dx:root-lobha': [('Grasping that sticks and will not let go',
                    ['I hold on too tightly',
                     'I hold on tight to it',
                     "I can't bear to lose it",
                     "I can't accept losing it",
                     "I can't let go of the people I love",
                     "I can't throw anything away"])],
 'dx:kasaya-lobha': [('Greed, one of the four passions',
                      ['I always want more money',
                       'what I earn is never enough',
                       "I'm never satisfied with what I earn",
                       "I can't bear spending",
                       'I hate spending on anything',
                       "I'm stingy with money",
                       'I keep buying things I do not need'])],
 'dx:gita-kama-krodha': [('A fire that cannot be filled',
                          ['I never feel satisfied and always want more'])],
 'dx:guna-rajas': [('When rajas grows',
                    ['I always want something bigger',
                     'I keep chasing the next big thing']),
                   ('Rājasa happiness',
                    ['I feel empty when the fun ends',
                     'I crash after the excitement fades'])],
 'dx:klesa-raga': [('Wanting a pleasure again',
                    ['I keep chasing that high',
                     'I miss it and want it again',
                     'I miss those moments',
                     'I keep looking at the photos',
                     'I relive those memories',
                     'I replay the good memories',
                     'I crave the excitement again'])],
 'dx:tanha': [('Delighting now here, now there',
               ['I chase the next thrill',
                "I'm always chasing the next thing"])],
 'dx:jain-arta-dhyana': [('The mind fixed on getting back',
                          ['I miss what I lost',
                           'I keep wanting them back',
                           'I pine for the person I lost']),
                         ('The mind fixed on future enjoyments',
                          ["I'm already planning the next trip",
                           'I daydream about my next holiday'])],
 'dx:mutthassati': [('Mindfulness muddled',
                     ['I zone out when I read'])],
}


def _merge_p6() -> None:
    for eid, specs in NEW_P6.items():
        have = NEW.setdefault(eid, [])
        for prefix, cues in specs:
            for p, lst in have:
                if p == prefix:
                    lst.extend(c for c in cues if c not in lst)
                    break
            else:
                have.append((prefix, list(cues)))
        prefixes = [p for p, _ in have]
        for i, a in enumerate(prefixes):
            for b in prefixes[i + 1:]:
                assert not (a.startswith(b) or b.startswith(a)), f"{eid}: two specs for one marker: {a!r} / {b!r}"


_merge_p6()
